name: "Build Commit"
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        steps:
            - uses: actions/checkout@v3.3.0
            - uses: actions/setup-java@v3.10.0
              with:
                  distribution: temurin
                  java-version: 17

            - run: echo $GOOGLE_SERVICES_JSON > /home/runner/work/ReadYou/ReadYou/app/google-services.json
            - uses: gradle/gradle-build-action@v2.4.2
            - run: gradle assembleRelease

            - uses: actions/upload-artifact@v3.1.1
              with:
                  name: ReadYou-GitHub-Build-${{ github.sha }}
                  path: app/build/outputs/apk/github/release/*.apk
